groups:
  - name: cloud-native-sample
    rules:
      - alert: HighOrderVolume
        expr: increase(cloud_native_sample_orders_created[1m]) > 5
        for: 30s
        labels:
          severity: high
        annotations:
          summary: High order Volume detected
          description: We've detected a high order volume on cn.thinktecture-demos.com ("{{ $value }}"). 
