rule_files:
  - /etc/prometheus/cn-alerting-rules.yml
alerting:
  alertmanagers:
  - static_configs:
    - targets: ["alertmanager:9093"]
scrape_configs:
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          - cadvisor:8080
  - job_name: apps
    scrape_interval: 10s
    static_configs:
      - targets:
          - gateway:5000
          - products:5000
          - orders:5000
          - shipping:5000
          - notification:5000
