apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "products.fullname" . }}
  labels:
    {{- include "products.labels" . | nindent 4 }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "products.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "products.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "products.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ProductsService__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: databases
                  key: products
                  optional: false
            - name: ProductsService__IdentityServer__Authority
              valueFrom:
                configMapKeyRef:
                  name: authentication
                  key: authority
                  optional: true
            - name: ProductsService__ExposePrometheusMetrics
              value: {{ .Values.exposePrometheusMetrics | quote }}
            - name: ProductsService__ZipkinEndpoint
              valueFrom:
                configMapKeyRef:
                  name: zipkin
                  key: endpoint
          ports:
            - name: http-products
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 20
            httpGet:
              path: /healthz/liveness
              port: http-products
          readinessProbe:
            initialDelaySeconds: 20
            timeoutSeconds: 3
            httpGet:
              path: /healthz/readiness
              port: http-products
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
