environment: Production
disableConsoleLog: false
image:
  repository: nginx
  tag: "alpine"
  
container:
  port: 5000
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 96Mi

annotations:
  dapr.io/enabled: "true"
  dapr.io/app-id: "ordermonitorservice"
  dapr.io/app-port: "5000"
  dapr.io/config: "cloud-native-sample"
  prometheus.io/scrape: 'true'
  prometheus.io/port: '5000'

nameOverride: ""
fullnameOverride: ""

service:
  port: 80

replicas: 1
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
