name: "CI/CD: FakeSMTP"
on:
  push:
    branches:
      - "main"
    paths:
      - "charts/fake-smtp/**"
      - ".github/workflows/cn.fakesmtp.ci.yml"
      - ".github/templates/**/*.yml"
  workflow_dispatch:
jobs:
  cd:
    name: "CD: FakeSMTP"
    runs-on: ubuntu-latest
    env:
      AKS_NAME: aks-cloud-native-sample
      RG_NAME: rg-cloud-native-sample-develop
      KUBELOGIN_VERSION: v0.0.24
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Deploy FakeSMTP
        uses: "./.github/templates/deploy"
        with:
          acr_name: ${{ secrets.ACR_NAME}}
          app_name: fakesmtp
          app_display_name: FakeSMTP
          helm_chart_location: ./charts/fake-smtp
          aks_name: ${{ env.AKS_NAME }}
          aks_resource_group_name: ${{ env.RG_NAME }}
          kubelogin_version: ${{ env.KUBELOGIN_VERSION }}
          kubernetes_namespace: fake-smtp
          github_token: ${{ secrets.github_token }}
          terraform_client_id: ${{ secrets.TERRAFORM_CLIENT_ID }}
          terraform_client_secret: ${{ secrets.TERRAFORM_CLIENT_SECRET }}
          terraform_subscription_id: ${{ secrets.TERRAFORM_SUBSCRIPTION_ID }}
          terraform_tenant_id: ${{ secrets.TERRAFORM_TENANT_ID }}
